name: Test
# 触发 workflow 的事件
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
# 一个workflow由执行的一项或多项job
jobs:
  # 一个job任务，任务名为build
  build:
    runs-on: ubuntu-latest
    #步骤合集
    steps:
      #检出代码到工作区
      - name: Checkout code
        uses: actions/checkout@v4
      #设置Python环境，pip依赖
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      #安装项目依赖
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      #运行测试
      - name: Run tests
        run: |
          python manage.py makemigrations
          python manage.py migrate
          python manage.py test
